apiVersion: v1
kind: Service

metadata:
  name: eks-microservice

spec:
  type: LoadBalancer

  selector:
    app: eks-microservice

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
